package com.androidcommondoc.gradle

import dev.detekt.gradle.Detekt
import dev.detekt.gradle.DetektCreateBaselineTask
import dev.detekt.gradle.extensions.DetektExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.testing.Test

/**
 * AndroidCommonDoc toolkit Gradle plugin.
 *
 * Equivalent to the former `androidcommondoc.toolkit.gradle.kts` precompiled script,
 * rewritten as a `Plugin<Project>` so it compiles with `java-gradle-plugin` +
 * `kotlin("jvm")` and resolves entirely from Maven Central — no Gradle Plugin Portal
 * access required. This makes it compatible with Gradle 8.x, Gradle 9.x, and
 * corporate environments where plugins.gradle.org is blocked by an SSL proxy.
 *
 * Plugin ID:  androidcommondoc.toolkit
 * Extension:  androidCommonDoc { ... }  (see [AndroidCommonDocExtension])
 */
class AndroidCommonDocToolkitPlugin : Plugin<Project> {

    override fun apply(target: Project) {
        with(target) {
            // Apply Detekt 2.0 plugin
            pluginManager.apply("dev.detekt")

            // Register the opt-out extension DSL
            val toolkitExt = extensions.create(
                "androidCommonDoc",
                AndroidCommonDocExtension::class.java
            )

            // Resolve AndroidCommonDoc root directory from ANDROID_COMMON_DOC env var.
            // Required because in a composite build the consuming project's rootProject
            // is NOT AndroidCommonDoc — we need an absolute path to locate the JAR + config.
            val commonDocRoot: String = System.getenv("ANDROID_COMMON_DOC")
                ?: error(
                    """
                    ANDROID_COMMON_DOC environment variable is not set.
                    Set it to the AndroidCommonDoc repository root, e.g.:
                      export ANDROID_COMMON_DOC=/path/to/AndroidCommonDoc
                    This is required for the plugin to locate the custom rules JAR and config.
                    """.trimIndent()
                )

            // Configure Detekt base settings
            extensions.getByType(DetektExtension::class.java).apply {
                buildUponDefaultConfig.set(true)
                parallel.set(true)

                // Load L0 baseline first, then L1 override (config.yml).
                // CompositeConfig(lookFirst=last, lookSecond=first) — last file wins per leaf key.
                // This matches the documented hierarchy: L0 base defines all rules active,
                // L1 override selectively disables rules per project.
                val l0Base = file("$commonDocRoot/detekt-rules/src/main/resources/config/detekt-l0-base.yml")
                val l1Override = file("$commonDocRoot/detekt-rules/src/main/resources/config/config.yml")

                when {
                    l0Base.exists() && l1Override.exists() -> config.setFrom(l0Base, l1Override)
                    l0Base.exists() -> config.setFrom(l0Base)
                    l1Override.exists() -> {
                        logger.warn(
                            "AndroidCommonDoc: detekt-l0-base.yml not found at {}. " +
                                "Falling back to config.yml only. Build the rules JAR first: " +
                                "cd {} && ./gradlew :detekt-rules:assemble",
                            l0Base.absolutePath,
                            commonDocRoot
                        )
                        config.setFrom(l1Override)
                    }
                    else -> logger.warn(
                        "AndroidCommonDoc: No Detekt config found at {}. " +
                            "Rules will rely on ServiceLoader defaults.",
                        "$commonDocRoot/detekt-rules/src/main/resources/config/"
                    )
                }
            }

            // In Detekt 2.0 + KMP, per-source-set tasks (detektCommonMainSourceSet,
            // detektAndroidMainSourceSet, etc.) are auto-generated by the Kotlin Gradle
            // Plugin integration. These tasks are of type Detekt_Decorated (a subclass of
            // Detekt) and do NOT inherit DetektExtension settings automatically — they
            // carry their own config and baseline inputs.
            //
            // Fix: configure ALL Detekt tasks (including auto-generated KMP ones) via
            // tasks.withType(Detekt). This runs after task registration so it catches
            // every task regardless of how it was created.
            //
            // Baseline per source set: Detekt 2.0 generates baseline tasks named
            // detektBaseline<SourceSetName> (e.g. detektBaselineCommonMainSourceSet).
            // Each produces its own XML (e.g. detekt-baseline-commonMainSourceSet.xml).
            // We map task name → expected baseline file using the same naming convention.
            afterEvaluate {
                val l0Base = file("$commonDocRoot/detekt-rules/src/main/resources/config/detekt-l0-base.yml")
                val l1Override = file("$commonDocRoot/detekt-rules/src/main/resources/config/config.yml")

                val configFiles = when {
                    l0Base.exists() && l1Override.exists() -> listOf(l0Base, l1Override)
                    l0Base.exists() -> listOf(l0Base)
                    l1Override.exists() -> listOf(l1Override)
                    else -> emptyList()
                }

                tasks.withType(Detekt::class.java).configureEach { detektTask ->
                    // Apply L0 + L1 config to every Detekt task including KMP source-set tasks.
                    // buildUponDefaultConfig must be set here too — the DetektExtension value
                    // is NOT propagated to auto-generated KMP tasks in Detekt 2.0-alpha.
                    detektTask.buildUponDefaultConfig.set(true)

                    if (configFiles.isNotEmpty()) {
                        detektTask.config.setFrom(configFiles)
                    }

                    // Map task name to per-source-set baseline XML.
                    // Convention: detektCommonMainSourceSet → detekt-baseline-commonMainSourceSet.xml
                    //             detekt (root task)       → detekt-baseline.xml
                    val taskName = detektTask.name
                    val baselineFile = when {
                        taskName == "detekt" -> projectDir.resolve("detekt-baseline.xml")
                        taskName.startsWith("detekt") -> {
                            // Strip "detekt" prefix, lowercase first char to get source-set suffix
                            val suffix = taskName.removePrefix("detekt")
                            val lcSuffix = suffix.replaceFirstChar { it.lowercase() }
                            projectDir.resolve("detekt-baseline-${lcSuffix}.xml")
                        }
                        else -> null
                    }

                    if (baselineFile != null && baselineFile.exists()) {
                        detektTask.baseline.set(baselineFile)
                    }
                }

                // Apply same config to DetektCreateBaselineTask so baseline generation
                // uses the correct rules (otherwise baseline is generated against defaults)
                tasks.withType(DetektCreateBaselineTask::class.java).configureEach { baselineTask ->
                    if (configFiles.isNotEmpty()) {
                        baselineTask.config.setFrom(configFiles)
                    }
                }
            }

            // Add detektPlugins dependencies after project evaluation so consuming
            // projects can set androidCommonDoc { ... } properties in their build script
            // before we read them (same afterEvaluate pattern as the precompiled script).
            afterEvaluate {
                if (toolkitExt.detektRules.get()) {
                    val rulesJar = file("$commonDocRoot/detekt-rules/build/libs/detekt-rules-1.0.0.jar")
                    if (rulesJar.exists()) {
                        dependencies.add("detektPlugins", files(rulesJar))
                    } else {
                        logger.warn(
                            "AndroidCommonDoc: Custom rules JAR not found at {}. " +
                                "Build it with: cd {} && ./gradlew assemble",
                            rulesJar.absolutePath,
                            "$commonDocRoot/detekt-rules"
                        )
                    }
                }

                if (toolkitExt.composeRules.get()) {
                    dependencies.add("detektPlugins", "io.nlopez.compose.rules:detekt:0.5.6")
                }

                if (toolkitExt.formattingRules.get()) {
                    dependencies.add("detektPlugins", "dev.detekt:detekt-rules-ktlint-wrapper:2.0.0-alpha.2")
                }
            }

            // Configure test conventions after evaluation (same opt-out pattern)
            afterEvaluate {
                if (toolkitExt.testConfig.get()) {
                    tasks.withType(Test::class.java).configureEach {
                        it.maxParallelForks = 1
                        it.useJUnitPlatform()
                    }
                }
            }
        }
    }
}
