import { describe, it, expect } from "vitest";
import {
  emitConfigEntry,
  emitFullConfig,
  emitBaselineConfig,
} from "../../../src/generation/config-emitter.js";
import type { RuleDefinition } from "../../../src/registry/types.js";

// ── Fixtures ─────────────────────────────────────────────────────────────────

const handWrittenRule: RuleDefinition = {
  id: "sealed-ui-state",
  type: "prefer-construct",
  message: "UiState must be sealed interface, not data class",
  detect: { class_suffix: "UiState", must_be: "sealed" },
  hand_written: true,
  source_rule: "SealedUiStateRule.kt",
};

const generatedRule: RuleDefinition = {
  id: "no-mocks-in-common-tests",
  type: "banned-import",
  message: "Use pure Kotlin fakes in commonTest, not Mockito or MockK",
  detect: {
    banned_import_prefixes: ["io.mockk", "org.mockito"],
    prefer: "pure Kotlin fake class",
  },
};

const generatedRule2: RuleDefinition = {
  id: "no-default-dispatcher-in-tests",
  type: "banned-usage",
  message: "Tests must inject TestDispatcher; never use Dispatchers.Default directly",
  detect: {
    banned_expression: "Dispatchers.Default",
    prefer: "injected testDispatcher parameter",
  },
};

// ── emitConfigEntry ──────────────────────────────────────────────────────────

describe("emitConfigEntry", () => {
  it("uses source_rule filename for hand-written rules", () => {
    const { ruleId, entry } = emitConfigEntry(handWrittenRule);
    expect(ruleId).toBe("SealedUiStateRule");
    expect(entry).toBe("  SealedUiStateRule:\n    active: true");
  });

  it("derives PascalCase class name for generated rules", () => {
    const { ruleId, entry } = emitConfigEntry(generatedRule);
    expect(ruleId).toBe("NoMocksInCommonTestsRule");
    expect(entry).toBe("  NoMocksInCommonTestsRule:\n    active: true");
  });

  it("handles hand_written without source_rule — derives PascalCase + Rule suffix", () => {
    const rule: RuleDefinition = {
      id: "some-rule",
      type: "banned-import",
      message: "msg",
      detect: {},
      hand_written: true,
      // source_rule intentionally omitted — falls back to generated naming
    };
    const { ruleId } = emitConfigEntry(rule);
    // toPascalCase("some-rule") = "SomeRule" + "Rule" suffix = "SomeRuleRule"
    // source_rule should always be set for hand-written rules to avoid this
    expect(ruleId).toBe("SomeRuleRule");
  });
});

// ── emitFullConfig ────────────────────────────────────────────────────────────

describe("emitFullConfig", () => {
  it("starts with AndroidCommonDoc section and active: true", () => {
    const result = emitFullConfig([handWrittenRule]);
    expect(result).toContain("AndroidCommonDoc:");
    expect(result).toContain("  active: true");
  });

  it("separates hand-written and generated rules", () => {
    const result = emitFullConfig([handWrittenRule, generatedRule]);
    const hwIdx = result.indexOf("# Hand-written rules");
    const genIdx = result.indexOf("# Generated rules");
    const hwRuleIdx = result.indexOf("SealedUiStateRule:");
    const genRuleIdx = result.indexOf("NoMocksInCommonTestsRule:");
    expect(hwIdx).toBeGreaterThan(-1);
    expect(genIdx).toBeGreaterThan(-1);
    expect(hwRuleIdx).toBeGreaterThan(hwIdx);
    expect(genRuleIdx).toBeGreaterThan(genIdx);
  });

  it("omits generated section when no generated rules", () => {
    const result = emitFullConfig([handWrittenRule]);
    expect(result).not.toContain("# Generated rules");
    expect(result).toContain("SealedUiStateRule:");
  });

  it("omits hand-written section when no hand-written rules", () => {
    const result = emitFullConfig([generatedRule]);
    expect(result).not.toContain("# Hand-written rules");
    expect(result).toContain("NoMocksInCommonTestsRule:");
  });
});

// ── emitBaselineConfig ───────────────────────────────────────────────────────

describe("emitBaselineConfig", () => {
  it("includes the header comment block", () => {
    const result = emitBaselineConfig([handWrittenRule]);
    expect(result).toContain("AndroidCommonDoc — L0 Baseline Detekt Configuration");
    expect(result).toContain("DO NOT EDIT THIS FILE MANUALLY");
  });

  it("includes override instructions in header", () => {
    const result = emitBaselineConfig([handWrittenRule]);
    expect(result).toContain("HOW TO OVERRIDE IN YOUR PROJECT");
    expect(result).toContain("config.from(");
    expect(result).toContain("active: false");
  });

  it("all rules are active: true in baseline", () => {
    const result = emitBaselineConfig([handWrittenRule, generatedRule, generatedRule2]);
    // Count 4-space-indented "    active: true" lines — rule-level entries only
    // (ruleset-level is 2-space; header comment text is not indented code)
    const ruleActiveLines = result.split("\n").filter(
      (line) => line === "    active: true"
    );
    expect(ruleActiveLines.length).toBe(3); // one per rule entry
  });

  it("includes inline message comment above each rule", () => {
    const result = emitBaselineConfig([handWrittenRule]);
    expect(result).toContain("# UiState must be sealed interface, not data class");
    expect(result).toContain("SealedUiStateRule:");
  });

  it("deduplicates rules with the same class name", () => {
    // Same rule appearing in multiple docs (common in L0)
    const duplicate: RuleDefinition = {
      ...handWrittenRule,
      message: "Duplicate entry from another doc",
    };
    const result = emitBaselineConfig([handWrittenRule, duplicate]);
    const count = (result.match(/SealedUiStateRule:/g) ?? []).length;
    expect(count).toBe(1);
  });

  it("separates hand-written and generated rule sections", () => {
    const result = emitBaselineConfig([handWrittenRule, generatedRule]);
    expect(result).toContain("── Hand-written rules");
    expect(result).toContain("── Generated rules");
    const hwIdx = result.indexOf("── Hand-written rules");
    const genIdx = result.indexOf("── Generated rules");
    expect(hwIdx).toBeLessThan(genIdx);
  });

  it("produces valid YAML structure for AndroidCommonDoc section", () => {
    const result = emitBaselineConfig([handWrittenRule, generatedRule]);
    expect(result).toContain("AndroidCommonDoc:");
    expect(result).toMatch(/^\s*active: true/m);
    expect(result).toContain("  SealedUiStateRule:");
    expect(result).toContain("  NoMocksInCommonTestsRule:");
  });

  it("returns empty ruleset section when no rules provided", () => {
    const result = emitBaselineConfig([]);
    expect(result).toContain("AndroidCommonDoc:");
    expect(result).toContain("  active: true");
    // No rule entries beyond the ruleset-level active flag
    expect(result).not.toContain("Rule:");
  });
});

// ── L0/L1 override contract ──────────────────────────────────────────────────

describe("L0/L1 override model — contract tests", () => {
  it("baseline has all rules active — L1 can selectively disable", () => {
    const rules = [handWrittenRule, generatedRule, generatedRule2];
    const baseline = emitBaselineConfig(rules);

    // Baseline: all active
    expect(baseline).toContain("SealedUiStateRule:");
    expect(baseline).toContain("NoMocksInCommonTestsRule:");
    expect(baseline).toContain("NoDefaultDispatcherInTestsRule:");

    // L1 override would look like this (just documenting the contract)
    const l1Override = `AndroidCommonDoc:\n  NoMocksInCommonTestsRule:\n    active: false`;
    // Detekt CompositeConfig(lookFirst=l1Override, lookSecond=baseline) resolves correctly
    // This test documents the pattern — the actual Detekt merge is runtime behavior
    expect(l1Override).toContain("active: false");
  });
});
