'use strict';
const assert = require('assert');
const path = require('path');
const test = require('node:test');
const { catalog, markdown, frontmatter } = require('../tools/generate-operational-catalog.cjs');

const ROOT = path.resolve(__dirname, '../..');

test('catalog is derived from canonical surfaces and includes the quality-gate entrypoint', () => {
  const result = catalog(ROOT);
  assert.strictEqual(result.schema, 'operational-surface-catalog/v1');
  assert.ok(result.skills.some((skill) => skill.name === 'quality-gate' && skill.claude_command));
  assert.ok(result.mcp_tools.includes('rate-limit-status'));
  assert.strictEqual(new Set(result.mcp_tools).size, result.mcp_tools.length);
  assert.ok(result.skills.every((skill) => !/^[>|](?:\s|$)/.test(skill.description)), 'catalog descriptions must contain text, not YAML scalar markers');
  assert.match(markdown(result), /Generated by `node scripts\/tools\/generate-operational-catalog\.cjs`/);
});

test('folded YAML descriptions render as text instead of the scalar marker', () => {
  const meta = frontmatter('---\nname: demo\ndescription: >\n  First line\n  second line.\ncopilot: false\n---\n');
  assert.strictEqual(meta.description, 'First line second line.');
});
