/**
 * Detekt configuration emitter for generated rules.
 *
 * Generates detekt config.yml entries for both generated and hand-written
 * rules under the AndroidCommonDoc rule set section.
 *
 * ## L0/L1 Config Hierarchy
 *
 * AndroidCommonDoc distributes `detekt-l0-base.yml` as the baseline config.
 * All rules are `active: true` in the baseline.
 *
 * Consumer projects (L1/L2) override only what they need to change:
 *
 * ```yaml
 * # detekt.yml (L1 project — only overrides)
 * AndroidCommonDoc:
 *   NoMocksInCommonTests:
 *     active: false   # "we use MockK intentionally"
 * ```
 *
 * Detekt merges configs via CompositeConfig (lookFirst=override, lookSecond=base):
 *   `detekt --config detekt-l0-base.yml,detekt.yml`
 *
 * The last file wins at the leaf key level. An L1 can override any individual
 * rule without touching the baseline.
 */

import type { RuleDefinition } from "../registry/types.js";

/** Header comment block for the generated detekt-l0-base.yml file. */
const BASELINE_HEADER = `# AndroidCommonDoc — L0 Baseline Detekt Configuration
#
# This file is the authoritative baseline for all AndroidCommonDoc Detekt rules.
# All rules are active: true by default.
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  HOW TO OVERRIDE IN YOUR PROJECT (L1/L2)                                │
# │                                                                         │
# │  1. In your project, configure Detekt to load both configs:             │
# │     detekt {                                                             │
# │       config.from(                                                       │
# │         resources.text.fromFile("detekt-l0-base.yml"),                  │
# │         file("detekt.yml")   // your project overrides                  │
# │       )                                                                  │
# │     }                                                                   │
# │                                                                         │
# │  2. In your detekt.yml, override only what you need to change:          │
# │     AndroidCommonDoc:                                                   │
# │       NoMocksInCommonTests:                                             │
# │         active: false  # "we use MockK intentionally"                  │
# │                                                                         │
# │  Rules not mentioned in your override file stay active (baseline wins). │
# │  The last config file wins at the individual rule key level.            │
# └─────────────────────────────────────────────────────────────────────────┘
#
# DO NOT EDIT THIS FILE MANUALLY.
# Generated by: mcp-server/src/generation/config-emitter.ts — emitBaselineConfig()
# Regenerate with: npm run generate-rules (or via the generate-rules MCP tool)
`;

/**
 * Convert a kebab-case rule ID to a PascalCase class name with Rule suffix.
 */
function toPascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

/**
 * Resolve the Kotlin class name for a rule definition.
 *
 * Hand-written rules use the explicit source_rule filename.
 * Generated rules derive the class name from the kebab-case rule ID.
 */
function resolveClassName(rule: RuleDefinition): string {
  return rule.hand_written && rule.source_rule
    ? rule.source_rule.replace(/\.kt$/, "")
    : toPascalCase(rule.id) + "Rule";
}

/**
 * Emit a single detekt config entry for a rule.
 *
 * @param rule - The rule definition
 * @returns Object with ruleId (class name) and the YAML config entry string
 */
export function emitConfigEntry(rule: RuleDefinition): {
  ruleId: string;
  entry: string;
} {
  const className = resolveClassName(rule);
  const entry = `  ${className}:\n    active: true`;
  return { ruleId: className, entry };
}

/**
 * Emit a complete AndroidCommonDoc config section for detekt config.yml.
 *
 * Includes both hand-written rules (with reference comments) and
 * generated rules. Hand-written rules are included in config but
 * their source files are not generated.
 *
 * @param rules - All rule definitions (both hand-written and generated)
 * @returns Complete YAML config section string
 */
export function emitFullConfig(rules: RuleDefinition[]): string {
  const lines: string[] = ["AndroidCommonDoc:", "  active: true"];

  const handWritten = rules.filter((r) => r.hand_written === true);
  const generated = rules.filter((r) => r.hand_written !== true);

  if (handWritten.length > 0) {
    lines.push("  # Hand-written rules");
    for (const rule of handWritten) {
      const { entry } = emitConfigEntry(rule);
      lines.push(entry);
    }
  }

  if (generated.length > 0) {
    lines.push("  # Generated rules");
    for (const rule of generated) {
      const { entry } = emitConfigEntry(rule);
      lines.push(entry);
    }
  }

  return lines.join("\n");
}

/**
 * Emit the L0 baseline detekt config file content.
 *
 * This is the distributable baseline for consumer projects.
 * All rules are active: true. Consumer projects override individual
 * rules in their own detekt.yml without modifying this file.
 *
 * Groups rules by category (hand-written vs generated) with inline comments.
 * Deduplicates rules — the same rule may appear in multiple pattern docs.
 *
 * @param rules - All rule definitions (both hand-written and generated)
 * @returns Full content for detekt-l0-base.yml, including header comment
 */
export function emitBaselineConfig(rules: RuleDefinition[]): string {
  // Deduplicate by class name — same rule can appear in multiple docs
  const seen = new Set<string>();
  const uniqueRules: RuleDefinition[] = [];
  for (const rule of rules) {
    const className = resolveClassName(rule);
    if (!seen.has(className)) {
      seen.add(className);
      uniqueRules.push(rule);
    }
  }

  const handWritten = uniqueRules.filter((r) => r.hand_written === true);
  const generated = uniqueRules.filter((r) => r.hand_written !== true);

  const lines: string[] = [
    BASELINE_HEADER,
    "AndroidCommonDoc:",
    "  active: true",
    "",
  ];

  if (handWritten.length > 0) {
    lines.push("  # ── Hand-written rules ─────────────────────────────────────────────────────");
    for (const rule of handWritten) {
      const className = resolveClassName(rule);
      lines.push(`  # ${rule.message}`);
      lines.push(`  ${className}:`);
      lines.push(`    active: true`);
      lines.push("");
    }
  }

  if (generated.length > 0) {
    lines.push("  # ── Generated rules ─────────────────────────────────────────────────────────");
    for (const rule of generated) {
      const className = resolveClassName(rule);
      lines.push(`  # ${rule.message}`);
      lines.push(`  ${className}:`);
      lines.push(`    active: true`);
      lines.push("");
    }
  }

  return lines.join("\n");
}
